Main:
    HttpPort: 80
    HttpsOn: true
    Domain: "2049bbs.xyz"
    HttpsPort: 443
    PubDir: "static"
    ViewDir: "view/default"
    Youdb: "mydata.db"
    CookieSecure: false
    CookieHttpOnly: true
    OldSiteDomain: ""
    TLSCrtFile: "certs/cloudflare.pem"
    TLSKeyFile: "certs/cloudflare.key"
Site:
    Name: "2049BBS"
    Desc: "Speak with no fear"
    AdminEmail: ""
    MainDomain: "http://2049bbs.xyz"
    MainNodeIds: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"
    TimeZone: 8
    HomeShowNum: 40
    PageShowNum: 20
    TagShowNum: 30
    CategoryShowNum: 20
    TitleMaxLen: 80
    ContentMaxLen: 20000
    PostInterval: 60
    CommentListNum: 100
    CommentInterval: 20
    Authorized: false
    RegReview: false
    CloseReg: false
    AutoDataBackup: true
    AutoGetTag: true
    UploadSuffix: ""
    UploadImgOnly: false
    UploadImgResize: false
    UploadMaxSize: 50
